######################################################################
# Automatically generated by qmake (2.01a) Fri Dec 10 10:55:24 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += QinEngine.h QVirtualKeyboard.h
FORMS += QVirtualKeyboard.ui
SOURCES += Qin.cpp QinEngine.cpp QVirtualKeyboard.cpp
